#+PROPERTY: header-args:jupyter-python  :session py :kernel python
#+PROPERTY: header-args    :pandoc t

* Imports
#+begin_src jupyter-python
import pandas as pd
import numpy as np
#+end_src

* Day 1
** Part 1
To do this, count the number of times a depth measurement increases from the previous measurement. (There is no measurement before the first measurement.)
#+begin_src jupyter-python
  data = pd.read_csv('data/1.csv', names=['depth'])
  (data.diff() > 0).sum()
#+end_src

** Part 2
Instead, consider sums of a three-measurement sliding window.  Your goal now is to count the number of times the sum of measurements in this sliding window increases from the previous sum. So, compare A with B, then compare B with C, then C with D, and so on. Stop when there aren't enough measurements left to create a new three-measurement sum.
#+begin_src jupyter-python
(data.rolling(3).sum().diff() > 0).sum()
#+end_src

* Day 2
** Part 1
It seems like the submarine can take a series of commands like forward 1, down 2, or up 3:

    - forward X increases the horizontal position by X units.
    - down X increases the depth by X units.
    - up X decreases the depth by X units.

Calculate the horizontal position and depth you would have after following the planned course. What do you get if you multiply your final horizontal position by your final depth?
#+begin_src jupyter-python
  data = pd.read_csv('data/2.csv', sep=' ', names=['instruction', 'amount'])
  totals = data.groupby('instruction').sum()
  totals.loc['forward'] * (totals.loc['down'] - totals.loc['up'])
#+end_src

** Part 2
In addition to horizontal position and depth, you'll also need to track a third value, aim, which also starts at 0. The commands also mean something entirely different than you first thought:

    - down X increases your aim by X units.
    - up X decreases your aim by X units.
    - forward X does two things:
        - It increases your horizontal position by X units.
        - It increases your depth by your aim multiplied by X.

Using this new interpretation of the commands, calculate the horizontal position and depth you would have after following the planned course. What do you get if you multiply your final horizontal position by your final depth?
#+begin_src jupyter-python
  state = (0, 0, 0)
  ops = {'down': lambda x, y: (x[0] + y, x[1], x[2]),
         'up': lambda x, y: (x[0] - y, x[1], x[2]),
         'forward': lambda x, y: (x[0], x[1] + y, x[2] + x[0]*y)}
  for row in data.itertuples():
      state = ops[row.instruction](state, row.amount)
  print(state[1] * state[2])
#+end_src

* Day 3

** Part 1
The diagnostic report (your puzzle input) consists of a list of binary numbers which, when decoded properly, can tell you many useful things about the conditions of the submarine. The first parameter to check is the power consumption.

You need to use the binary numbers in the diagnostic report to generate two new binary numbers (called the gamma rate and the epsilon rate). The power consumption can then be found by multiplying the gamma rate by the epsilon rate.

Each bit in the gamma rate can be determined by finding the most common bit in the corresponding position of all numbers in the diagnostic report. The epsilon rate is calculated in a similar way; rather than use the most common bit, the least common bit from each position is used.

Use the binary numbers in your diagnostic report to calculate the gamma rate and epsilon rate, then multiply them together.

#+begin_src jupyter-python
df = pd.read_fwf('data/3.csv', widths=[1]*12, header=None)
def binarize(array):
    return int(''.join(str(x) for x in array.reshape(-1)), 2)
bits = df.median().to_numpy(dtype=int)
binarize(bits) * binarize(1 - bits)
#+end_src

** Part 2
Both the oxygen generator rating and the CO2 scrubber rating are values that can be found in your diagnostic report - finding them is the tricky part. Both values are located using a similar process that involves filtering out values until only one remains. Before searching for either rating value, start with the full list of binary numbers from your diagnostic report and consider just the first bit of those numbers. Then:

    - Keep only numbers selected by the bit criteria for the type of rating value for which you are searching. Discard numbers which do not match the bit criteria.
    - If you only have one number left, stop; this is the rating value for which you are searching.
    - Otherwise, repeat the process, considering the next bit to the right.

The bit criteria depends on which type of rating value you want to find:

    - To find oxygen generator rating, determine the most common value (0 or 1) in the current bit position, and keep only numbers with that bit in that position. If 0 and 1 are equally common, keep values with a 1 in the position being considered.
    - To find CO2 scrubber rating, determine the least common value (0 or 1) in the current bit position, and keep only numbers with that bit in that position. If 0 and 1 are equally common, keep values with a 0 in the position being considered.

Use the binary numbers in your diagnostic report to calculate the oxygen generator rating and CO2 scrubber rating, then multiply them together.

#+begin_src jupyter-python
oxygen = df
co2 = df
for column in df.columns:
    oxygen = oxygen[oxygen[column] == int(oxygen[column].median() + 0.5)]
    if len(co2) > 1:
        co2 = co2[co2[column] != int(co2[column].median() + 0.5)]
binarize(oxygen.to_numpy()) * binarize(co2.to_numpy())
#+end_src

* Day 4

** Part 1
Bingo is played on a set of boards each consisting of a 5x5 grid of numbers. Numbers are chosen at random, and the chosen number is marked on all boards on which it appears. (Numbers may not appear on all boards.) If all numbers in any row or any column of a board are marked, that board wins. (Diagonals don't count.)

The score of the winning board can now be calculated. Start by finding the sum of all unmarked numbers on that board. Then, multiply that sum by the number that was just called when the board won, to get the final score

To guarantee victory against the giant squid, figure out which board will win first. What will your final score be if you choose that board?

#+begin_src jupyter-python
  numbers = np.loadtxt('data/4.txt', delimiter=',', max_rows=1)
  boards = np.loadtxt('data/4.txt', skiprows=2).reshape(-1, 5, 5)

  def winning_array(boards):
      return ((boards == -1).all(axis=2) | (boards == -1).all(axis=1)).any(axis=1)

  for number in numbers:
      boards[np.where(boards == number)] = -1
      if winning_array(boards).any():
          break
  index = np.where(winning_array(boards))
  np.sum(np.ma.array(boards, mask=(boards == -1))[index]) * number
#+end_src

** Part 2
Figure out which board will win last. Once it wins, what would its final score be?

#+begin_src jupyter-python
  for number in numbers:
      boards[np.where(boards == number)] = -1
      wins = winning_array(boards)
      if wins.sum() == len(boards) - 1:
          index = np.where(~wins)[0]
      if wins.all():
          break
  np.sum(np.ma.array(boards, mask=(boards == -1))[index]) * number
#+end_src

* Day 5

** Part 1
You come across a field of hydrothermal vents on the ocean floor! These vents constantly produce large, opaque clouds, so it would be best to avoid them if possible.

They tend to form in lines; the submarine helpfully produces a list of nearby lines of vents (your puzzle input) for you to review.

Each line of vents is given as a line segment in the format x1,y1 -> x2,y2 where x1,y1 are the coordinates of one end the line segment and x2,y2 are the coordinates of the other end. These line segments include the points at both ends. In other words:

    An entry like 1,1 -> 1,3 covers points 1,1, 1,2, and 1,3.
    An entry like 9,7 -> 7,7 covers points 9,7, 8,7, and 7,7.

For now, only consider horizontal and vertical lines: lines where either x1 = x2 or y1 = y2.

To avoid the most dangerous areas, you need to determine the number of points where at least two lines overlap.

Consider only horizontal and vertical lines. At how many points do at least two lines overlap?
#+begin_src jupyter-python
  data = pd.read_csv('data/5.txt', names=['x1', 'middle', 'y2'])
  data[['y1', 'x2']] = data['middle'].apply(lambda x: pd.Series(x.split('->')).astype('int'))
  grid = np.zeros((1000, 1000))

  def endpoints_to_line(x1, x2, y1, y2):
      steps = max(abs(x1 - x2), abs(y1- y2))
      delta = np.array([np.sign(x2 - x1), np.sign(y2 - y1)])
      points = [np.array([x1, y1]) + delta * n for n in range(steps + 1)]
      return tuple(np.array(points).T.tolist())

  on_axis = data[(data['x1'] == data['x2']) | (data['y1'] == data['y2'])]
  for row in on_axis.itertuples():
      grid[endpoints_to_line(row.x1, row.x2, row.y1, row.y2)] += 1

  (grid > 1).sum()
#+end_src

** Part 2
Unfortunately, considering only horizontal and vertical lines doesn't give you the full picture; you need to also consider diagonal lines.

Consider all of the lines. At how many points do at least two lines overlap?
#+begin_src jupyter-python
  skewed = data[(data['x1'] != data['x2']) & (data['y1'] != data['y2'])]
  for row in skewed.itertuples():
      grid[endpoints_to_line(row.x1, row.x2, row.y1, row.y2)] += 1

  (grid > 1).sum()
#+end_src

* Day 6

** Part 1
Although you know nothing about this specific species of lanternfish, you make some guesses about their attributes. Surely, each lanternfish creates a new lanternfish once every 7 days.

However, this process isn't necessarily synchronized between every lanternfish - one lanternfish might have 2 days left until it creates another lanternfish, while another might have 4. So, you can model each fish as a single number that represents the number of days until it creates a new lanternfish.

Furthermore, you reason, a new lanternfish would surely need slightly longer before it's capable of producing more lanternfish: two more days for its first cycle.

A lanternfish that creates a new fish resets its timer to 6, not 7 (because 0 is included as a valid timer value). The new lanternfish starts with an internal timer of 8 and does not start counting down until the next day.

Realizing what you're trying to do, the submarine automatically produces a list of the ages of several hundred nearby lanternfish (your puzzle input).

Each day, a 0 becomes a 6 and adds a new 8 to the end of the list, while each other number decreases by 1 if it was present at the start of the day.

Find a way to simulate lanternfish. How many lanternfish would there be after 80 days?
#+begin_src jupyter-python
  data = np.loadtxt('data/6.txt', delimiter=',', dtype=int)
  population, _ = np.histogram(data, range(10))
  transition_matrix = np.roll(np.eye(9, dtype=int), 1, axis=1)
  transition_matrix[6, 0] = 1
  (np.linalg.matrix_power(transition_matrix, 80) @ population).sum()
#+end_src

** Part 2
Suppose the lanternfish live forever and have unlimited food and space. Would they take over the entire ocean?

How many lanternfish would there be after 256 days?
#+begin_src jupyter-python
    (np.linalg.matrix_power(transition_matrix, 256) @ population).sum()
#+end_src
* Day 7
** Part 1
A giant whale has decided your submarine is its next meal, and it's much faster than you are. There's nowhere to run!

Suddenly, a swarm of crabs (each in its own tiny submarine - it's too deep for them otherwise) zooms in to rescue you! They seem to be preparing to blast a hole in the ocean floor; sensors indicate a massive underground cave system just beyond where they're aiming!

The crab submarines all need to be aligned before they'll have enough power to blast a large enough hole for your submarine to get through. However, it doesn't look like they'll be aligned before the whale catches you! Maybe you can help?

There's one major catch - crab submarines can only move horizontally.

You quickly make a list of the horizontal position of each crab (your puzzle input). Crab submarines have limited fuel, so you need to find a way to make all of their horizontal positions match while requiring them to spend as little fuel as possible.

Each change of 1 step in horizontal position of a single crab costs 1 fuel.

Determine the horizontal position that the crabs can align to using the least fuel possible. How much fuel must they spend to align to that position?
#+begin_src jupyter-python
  data = np.loadtxt('data/7.csv', delimiter=',', dtype=int)
  np.abs(data - np.median(data)).sum()
#+end_src
** Part 2
The crabs don't seem interested in your proposed solution. Perhaps you misunderstand crab engineering?

As it turns out, crab submarine engines don't burn fuel at a constant rate. Instead, each change of 1 step in horizontal position costs 1 more unit of fuel than the last: the first step costs 1, the second step costs 2, the third step costs 3, and so on.

Determine the horizontal position that the crabs can align to using the least fuel possible so they can make you an escape route! How much fuel must they spend to align to that position?
#+begin_src jupyter-python
  def cost(position):
      delta = np.abs(data - position)
      return ((delta) * (delta + 1) / 2).sum()

  options = [cost(int(data.mean())), cost(int(data.mean() + 0.5))]
  min(options)
#+end_src
