#+PROPERTY: header-args:jupyter-python  :session py :kernel python
#+PROPERTY: header-args    :pandoc t

* Imports
#+begin_src jupyter-python
import pandas as pd
import numpy as np
#+end_src

* Day 1
** Part 1
As the submarine drops below the surface of the ocean, it automatically performs a sonar sweep of the nearby sea floor. On a small screen, the sonar sweep report (your puzzle input) appears: each line is a measurement of the sea floor depth as the sweep looks further and further away from the submarine.

The first order of business is to figure out how quickly the depth increases, just so you know what you're dealing with - you never know if the keys will get carried into deeper water by an ocean current or a fish or something.

To do this, count the number of times a depth measurement increases from the previous measurement. (There is no measurement before the first measurement.)
#+begin_src jupyter-python
  data = pd.read_csv('data/1.csv', names=['depth'])
  (data.diff() > 0).sum()
#+end_src

** Part 2

Considering every single measurement isn't as useful as you expected: there's just too much noise in the data.

Instead, consider sums of a three-measurement sliding window.  Your goal now is to count the number of times the sum of measurements in this sliding window increases from the previous sum. So, compare A with B, then compare B with C, then C with D, and so on. Stop when there aren't enough measurements left to create a new three-measurement sum.
#+begin_src jupyter-python
(data.rolling(3).sum().diff() > 0).sum()
#+end_src

* Day 2
** Part 1
Now, you need to figure out how to pilot this thing.

It seems like the submarine can take a series of commands like forward 1, down 2, or up 3:

    - forward X increases the horizontal position by X units.
    - down X increases the depth by X units.
    - up X decreases the depth by X units.

Calculate the horizontal position and depth you would have after following the planned course. What do you get if you multiply your final horizontal position by your final depth?
#+begin_src jupyter-python
  data = pd.read_csv('data/2.csv', sep=' ', names=['instruction', 'amount'])
  totals = data.groupby('instruction').sum()
  totals.loc['forward'] * (totals.loc['down'] - totals.loc['up'])
#+end_src

** Part 2
Based on your calculations, the planned course doesn't seem to make any sense. You find the submarine manual and discover that the process is actually slightly more complicated.

In addition to horizontal position and depth, you'll also need to track a third value, aim, which also starts at 0. The commands also mean something entirely different than you first thought:

    - down X increases your aim by X units.
    - up X decreases your aim by X units.
    - forward X does two things:
        - It increases your horizontal position by X units.
        - It increases your depth by your aim multiplied by X.

Using this new interpretation of the commands, calculate the horizontal position and depth you would have after following the planned course. What do you get if you multiply your final horizontal position by your final depth?

#+begin_src jupyter-python
  state = (0, 0, 0)
  ops = {'down': lambda x, y: (x[0] + y, x[1], x[2]),
         'up': lambda x, y: (x[0] - y, x[1], x[2]),
         'forward': lambda x, y: (x[0], x[1] + y, x[2] + x[0]*y)}
  for row in data.itertuples():
      state = ops[row.instruction](state, row.amount)
  print(state[1] * state[2])
#+end_src

* Day 3

** Part 1
The submarine has been making some odd creaking noises, so you ask it to produce a diagnostic report just in case.

The diagnostic report (your puzzle input) consists of a list of binary numbers which, when decoded properly, can tell you many useful things about the conditions of the submarine. The first parameter to check is the power consumption.

You need to use the binary numbers in the diagnostic report to generate two new binary numbers (called the gamma rate and the epsilon rate). The power consumption can then be found by multiplying the gamma rate by the epsilon rate.

Each bit in the gamma rate can be determined by finding the most common bit in the corresponding position of all numbers in the diagnostic report. The epsilon rate is calculated in a similar way; rather than use the most common bit, the least common bit from each position is used.

Use the binary numbers in your diagnostic report to calculate the gamma rate and epsilon rate, then multiply them together. What is the power consumption of the submarine? (Be sure to represent your answer in decimal, not binary.)

#+begin_src jupyter-python
df = pd.read_fwf('data/3.csv', widths=[1]*12, header=None)
def binarize(array):
    return int(''.join(str(x) for x in array.reshape(-1)), 2)
bits = df.median().to_numpy(dtype=int)
binarize(bits) * binarize(1 - bits)
#+end_src

** Part 2

Next, you should verify the life support rating, which can be determined by multiplying the oxygen generator rating by the CO2 scrubber rating.

Both the oxygen generator rating and the CO2 scrubber rating are values that can be found in your diagnostic report - finding them is the tricky part. Both values are located using a similar process that involves filtering out values until only one remains. Before searching for either rating value, start with the full list of binary numbers from your diagnostic report and consider just the first bit of those numbers. Then:

    - Keep only numbers selected by the bit criteria for the type of rating value for which you are searching. Discard numbers which do not match the bit criteria.
    - If you only have one number left, stop; this is the rating value for which you are searching.
    - Otherwise, repeat the process, considering the next bit to the right.

The bit criteria depends on which type of rating value you want to find:

    - To find oxygen generator rating, determine the most common value (0 or 1) in the current bit position, and keep only numbers with that bit in that position. If 0 and 1 are equally common, keep values with a 1 in the position being considered.
    - To find CO2 scrubber rating, determine the least common value (0 or 1) in the current bit position, and keep only numbers with that bit in that position. If 0 and 1 are equally common, keep values with a 0 in the position being considered.

Use the binary numbers in your diagnostic report to calculate the oxygen generator rating and CO2 scrubber rating, then multiply them together. What is the life support rating of the submarine? (Be sure to represent your answer in decimal, not binary.)

#+begin_src jupyter-python
oxygen = df
co2 = df
for column in df.columns:
    oxygen = oxygen[oxygen[column] == int(oxygen[column].median() + 0.5)]
    if len(co2) > 1:
        co2 = co2[co2[column] != int(co2[column].median() + 0.5)]
binarize(oxygen.to_numpy()) * binarize(co2.to_numpy())
#+end_src

* Day 4

** Part 1
You're already almost 1.5km (almost a mile) below the surface of the ocean, already so deep that you can't see any sunlight. What you can see, however, is a giant squid that has attached itself to the outside of your submarine.

Maybe it wants to play bingo?

Bingo is played on a set of boards each consisting of a 5x5 grid of numbers. Numbers are chosen at random, and the chosen number is marked on all boards on which it appears. (Numbers may not appear on all boards.) If all numbers in any row or any column of a board are marked, that board wins. (Diagonals don't count.)

The score of the winning board can now be calculated. Start by finding the sum of all unmarked numbers on that board. Then, multiply that sum by the number that was just called when the board won, to get the final score

To guarantee victory against the giant squid, figure out which board will win first. What will your final score be if you choose that board?

#+begin_src jupyter-python
  numbers = np.loadtxt('data/4.txt', delimiter=',', max_rows=1)
  boards = np.loadtxt('data/4.txt', skiprows=2).reshape(-1, 5, 5)

  def winning_array(boards):
      return ((boards == -1).all(axis=2) | (boards == -1).all(axis=1)).any(axis=1)

  for number in numbers:
      boards[np.where(boards == number)] = -1
      if winning_array(boards).any():
          break
  index = np.where(winning_array(boards))
  np.sum(np.ma.array(boards, mask=(boards == -1))[index]) * number
#+end_src

** Part 2
On the other hand, it might be wise to try a different strategy: let the giant squid win.

You aren't sure how many bingo boards a giant squid could play at once, so rather than waste time counting its arms, the safe thing to do is to figure out which board will win last and choose that one. That way, no matter which boards it picks, it will win for sure.

Figure out which board will win last. Once it wins, what would its final score be?

#+begin_src jupyter-python
  for number in numbers:
      boards[np.where(boards == number)] = -1
      wins = winning_array(boards)
      if wins.sum() == len(boards) - 1:
          index = np.where(~wins)[0]
      if wins.all():
          break
  np.sum(np.ma.array(boards, mask=(boards == -1))[index]) * number
#+end_src

* Day 5

** Part 1
You come across a field of hydrothermal vents on the ocean floor! These vents constantly produce large, opaque clouds, so it would be best to avoid them if possible.

They tend to form in lines; the submarine helpfully produces a list of nearby lines of vents (your puzzle input) for you to review.

Each line of vents is given as a line segment in the format x1,y1 -> x2,y2 where x1,y1 are the coordinates of one end the line segment and x2,y2 are the coordinates of the other end. These line segments include the points at both ends. In other words:

    An entry like 1,1 -> 1,3 covers points 1,1, 1,2, and 1,3.
    An entry like 9,7 -> 7,7 covers points 9,7, 8,7, and 7,7.

For now, only consider horizontal and vertical lines: lines where either x1 = x2 or y1 = y2.

To avoid the most dangerous areas, you need to determine the number of points where at least two lines overlap.

Consider only horizontal and vertical lines. At how many points do at least two lines overlap?
#+begin_src jupyter-python
  data = pd.read_csv('data/5.txt', names=['x1', 'middle', 'y2'])
  data[['y1', 'x2']] = data['middle'].apply(lambda x: pd.Series(x.split('->')).astype('int'))
  grid = np.zeros((1000, 1000))

  def endpoints_to_line(x1, x2, y1, y2):
      steps = max(abs(x1 - x2), abs(y1- y2))
      delta = np.array([np.sign(x2 - x1), np.sign(y2 - y1)])
      points = [np.array([x1, y1]) + delta * n for n in range(steps + 1)]
      return tuple(np.array(points).T.tolist())

  on_axis = data[(data['x1'] == data['x2']) | (data['y1'] == data['y2'])]
  for row in on_axis.itertuples():
      grid[endpoints_to_line(row.x1, row.x2, row.y1, row.y2)] += 1

  (grid > 1).sum()
#+end_src

** Part 2
Unfortunately, considering only horizontal and vertical lines doesn't give you the full picture; you need to also consider diagonal lines.

Because of the limits of the hydrothermal vent mapping system, the lines in your list will only ever be horizontal, vertical, or a diagonal line at exactly 45 degrees. In other words:

    An entry like 1,1 -> 3,3 covers points 1,1, 2,2, and 3,3.
    An entry like 9,7 -> 7,9 covers points 9,7, 8,8, and 7,9.

Consider all of the lines. At how many points do at least two lines overlap?
#+begin_src jupyter-python
  skewed = data[(data['x1'] != data['x2']) & (data['y1'] != data['y2'])]
  for row in skewed.itertuples():
      grid[endpoints_to_line(row.x1, row.x2, row.y1, row.y2)] += 1

  (grid > 1).sum()
#+end_src
